[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  NODE_VERSION = "20"

[context.production.environment]
  HUGO_VERSION = "0.125.7"
